from machine import Pin
from typing import Any, Dict, Optional, Sequence, Tuple, Union

Node = Any

class NeoPixel:
    def __init__(self, pin: Pin, num: int, bpp: int = 3): ...
    def __setitem__(
        self, key: int, value: Union[Tuple[int, int, int], Tuple[int, int, int, int]]
    ): ...
    def fill() -> None: ...
    def write() -> None: ...

def neopixel_write() -> None: ...
