from typing import Any, Dict, Optional, Sequence, Tuple, Union

Node = Any

def calcsize() -> None: ...
def pack() -> None: ...
def pack_into() -> None: ...
def unpack() -> None: ...
def unpack_from(
    format: str, data: Union[bytes, str, bytearray], offset: int = 0
) -> tuple: ...
